server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/excel_manager?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: aaa1024
logging:

  level:
    root: debug

